--------------------------------------------------------
--  파일이 생성됨 - 화요일-12월-08-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence BOARD_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BOOT"."BOARD_SEQ"  MINVALUE 1 MAXVALUE 10000 INCREMENT BY 1 START WITH 101 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence COMMENT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BOOT"."COMMENT_SEQ"  MINVALUE 1 MAXVALUE 10000 INCREMENT BY 1 START WITH 81 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table BOARD
--------------------------------------------------------

  CREATE TABLE "BOOT"."BOARD" 
   (	"BOARD_NUM" NUMBER(3,0), 
	"BOARD_WRITER" VARCHAR2(12 BYTE), 
	"BOARD_SUBJECT" VARCHAR2(300 BYTE), 
	"BOARD_CONTENT" VARCHAR2(4000 BYTE), 
	"BOARD_DATE" TIMESTAMP (6) DEFAULT SYSDATE, 
	"BOARD_FILE" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table BOARD_COMMENT
--------------------------------------------------------

  CREATE TABLE "BOOT"."BOARD_COMMENT" 
   (	"COMMENT_NUM" NUMBER(3,0), 
	"COMMENT_WRITER" VARCHAR2(12 BYTE), 
	"COMMENT_CONTENT" VARCHAR2(4000 BYTE), 
	"COMMENT_DATE" TIMESTAMP (6) DEFAULT SYSDATE, 
	"BOARD_NUM" NUMBER(3,0), 
	"COMMENT_REF" NUMBER(3,0) DEFAULT 0, 
	"COMMENT_LEVEL" NUMBER(3,0) DEFAULT 0, 
	"COMMENT_LENGTH" NUMBER(3,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "BOOT"."MEMBER" 
   (	"ID" VARCHAR2(12 BYTE), 
	"PWD" VARCHAR2(255 BYTE), 
	"ENABLED" NUMBER(1,0) DEFAULT 1, 
	"AUTHORITY" VARCHAR2(12 BYTE) DEFAULT 'MEMBER'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table START_TABLE
--------------------------------------------------------

  CREATE TABLE "BOOT"."START_TABLE" 
   (	"SUBJECT" VARCHAR2(10 BYTE), 
	"POST" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into BOOT.BOARD
SET DEFINE OFF;
Insert into BOOT.BOARD (BOARD_NUM,BOARD_WRITER,BOARD_SUBJECT,BOARD_CONTENT,BOARD_DATE,BOARD_FILE) values (81,'hello','이벤트 당첨되었다!!','헤드셋 내꺼!!',to_timestamp('20/12/08 11:28:14.000000000','RR/MM/DD HH24:MI:SSXFF'),'리턴.PNG');
Insert into BOOT.BOARD (BOARD_NUM,BOARD_WRITER,BOARD_SUBJECT,BOARD_CONTENT,BOARD_DATE,BOARD_FILE) values (82,'hello','이벤트 당첨되었다!!','헤드셋 내꺼!!',to_timestamp('20/12/08 11:28:34.000000000','RR/MM/DD HH24:MI:SSXFF'),'리턴.PNG');
Insert into BOOT.BOARD (BOARD_NUM,BOARD_WRITER,BOARD_SUBJECT,BOARD_CONTENT,BOARD_DATE,BOARD_FILE) values (83,'hello','이벤트 당첨되었다!!','헤드셋 내꺼!!',to_timestamp('20/12/08 11:30:22.000000000','RR/MM/DD HH24:MI:SSXFF'),'리턴.PNG');
Insert into BOOT.BOARD (BOARD_NUM,BOARD_WRITER,BOARD_SUBJECT,BOARD_CONTENT,BOARD_DATE,BOARD_FILE) values (84,'hello','이벤트 당첨되었다!!','헤드셋 내꺼!!',to_timestamp('20/12/08 11:32:12.000000000','RR/MM/DD HH24:MI:SSXFF'),'리턴.PNG');
Insert into BOOT.BOARD (BOARD_NUM,BOARD_WRITER,BOARD_SUBJECT,BOARD_CONTENT,BOARD_DATE,BOARD_FILE) values (21,'hello','안녕','내용입니다',to_timestamp('20/11/26 22:04:21.000000000','RR/MM/DD HH24:MI:SSXFF'),null);
Insert into BOOT.BOARD (BOARD_NUM,BOARD_WRITER,BOARD_SUBJECT,BOARD_CONTENT,BOARD_DATE,BOARD_FILE) values (23,'hello','안녕','내용입니다',to_timestamp('20/11/26 22:04:23.000000000','RR/MM/DD HH24:MI:SSXFF'),null);
Insert into BOOT.BOARD (BOARD_NUM,BOARD_WRITER,BOARD_SUBJECT,BOARD_CONTENT,BOARD_DATE,BOARD_FILE) values (26,'hello','안녕','내용입니다',to_timestamp('20/11/26 22:04:24.000000000','RR/MM/DD HH24:MI:SSXFF'),null);
Insert into BOOT.BOARD (BOARD_NUM,BOARD_WRITER,BOARD_SUBJECT,BOARD_CONTENT,BOARD_DATE,BOARD_FILE) values (27,'hello','안녕','내용입니다',to_timestamp('20/11/26 22:04:24.000000000','RR/MM/DD HH24:MI:SSXFF'),null);
Insert into BOOT.BOARD (BOARD_NUM,BOARD_WRITER,BOARD_SUBJECT,BOARD_CONTENT,BOARD_DATE,BOARD_FILE) values (29,'hello','안녕','내용입니다',to_timestamp('20/11/26 22:04:24.000000000','RR/MM/DD HH24:MI:SSXFF'),null);
Insert into BOOT.BOARD (BOARD_NUM,BOARD_WRITER,BOARD_SUBJECT,BOARD_CONTENT,BOARD_DATE,BOARD_FILE) values (30,'hello','안녕','내용입니다',to_timestamp('20/11/26 22:04:25.000000000','RR/MM/DD HH24:MI:SSXFF'),null);
Insert into BOOT.BOARD (BOARD_NUM,BOARD_WRITER,BOARD_SUBJECT,BOARD_CONTENT,BOARD_DATE,BOARD_FILE) values (31,'hello','안녕','내용입니다',to_timestamp('20/11/26 22:04:25.000000000','RR/MM/DD HH24:MI:SSXFF'),null);
Insert into BOOT.BOARD (BOARD_NUM,BOARD_WRITER,BOARD_SUBJECT,BOARD_CONTENT,BOARD_DATE,BOARD_FILE) values (32,'hello','안녕','내용입니다',to_timestamp('20/11/26 22:04:25.000000000','RR/MM/DD HH24:MI:SSXFF'),null);
Insert into BOOT.BOARD (BOARD_NUM,BOARD_WRITER,BOARD_SUBJECT,BOARD_CONTENT,BOARD_DATE,BOARD_FILE) values (33,'hello','안녕','내용입니다',to_timestamp('20/11/26 22:04:25.000000000','RR/MM/DD HH24:MI:SSXFF'),null);
Insert into BOOT.BOARD (BOARD_NUM,BOARD_WRITER,BOARD_SUBJECT,BOARD_CONTENT,BOARD_DATE,BOARD_FILE) values (34,'hello','안녕','내용입니다',to_timestamp('20/11/26 22:04:26.000000000','RR/MM/DD HH24:MI:SSXFF'),null);
Insert into BOOT.BOARD (BOARD_NUM,BOARD_WRITER,BOARD_SUBJECT,BOARD_CONTENT,BOARD_DATE,BOARD_FILE) values (35,'hello','안녕','내용입니다',to_timestamp('20/11/26 22:04:26.000000000','RR/MM/DD HH24:MI:SSXFF'),null);
Insert into BOOT.BOARD (BOARD_NUM,BOARD_WRITER,BOARD_SUBJECT,BOARD_CONTENT,BOARD_DATE,BOARD_FILE) values (36,'hello','안녕','내용입니다',to_timestamp('20/11/26 22:04:26.000000000','RR/MM/DD HH24:MI:SSXFF'),null);
Insert into BOOT.BOARD (BOARD_NUM,BOARD_WRITER,BOARD_SUBJECT,BOARD_CONTENT,BOARD_DATE,BOARD_FILE) values (37,'hello','안녕','내용입니다',to_timestamp('20/11/26 22:04:26.000000000','RR/MM/DD HH24:MI:SSXFF'),null);
Insert into BOOT.BOARD (BOARD_NUM,BOARD_WRITER,BOARD_SUBJECT,BOARD_CONTENT,BOARD_DATE,BOARD_FILE) values (38,'hello','안녕','내용입니다',to_timestamp('20/11/26 22:04:26.000000000','RR/MM/DD HH24:MI:SSXFF'),null);
Insert into BOOT.BOARD (BOARD_NUM,BOARD_WRITER,BOARD_SUBJECT,BOARD_CONTENT,BOARD_DATE,BOARD_FILE) values (39,'hello','안녕','내용입니다',to_timestamp('20/11/26 22:04:27.000000000','RR/MM/DD HH24:MI:SSXFF'),null);
Insert into BOOT.BOARD (BOARD_NUM,BOARD_WRITER,BOARD_SUBJECT,BOARD_CONTENT,BOARD_DATE,BOARD_FILE) values (40,'hello','안녕','내용입니다',to_timestamp('20/11/26 22:04:27.000000000','RR/MM/DD HH24:MI:SSXFF'),null);
Insert into BOOT.BOARD (BOARD_NUM,BOARD_WRITER,BOARD_SUBJECT,BOARD_CONTENT,BOARD_DATE,BOARD_FILE) values (41,'hello','좋은 날씨','오늘 날씨가 참 맑아요',to_timestamp('20/11/27 11:07:07.000000000','RR/MM/DD HH24:MI:SSXFF'),null);
Insert into BOOT.BOARD (BOARD_NUM,BOARD_WRITER,BOARD_SUBJECT,BOARD_CONTENT,BOARD_DATE,BOARD_FILE) values (42,'hello','좋은 날씨','오늘 날씨가 참 맑아요',to_timestamp('20/11/27 11:07:08.000000000','RR/MM/DD HH24:MI:SSXFF'),null);
Insert into BOOT.BOARD (BOARD_NUM,BOARD_WRITER,BOARD_SUBJECT,BOARD_CONTENT,BOARD_DATE,BOARD_FILE) values (46,'hello','좋은 날씨','오늘 날씨가 참 맑아요',to_timestamp('20/11/27 11:07:08.000000000','RR/MM/DD HH24:MI:SSXFF'),null);
Insert into BOOT.BOARD (BOARD_NUM,BOARD_WRITER,BOARD_SUBJECT,BOARD_CONTENT,BOARD_DATE,BOARD_FILE) values (47,'hello','좋은 날씨','오늘 날씨가 참 맑아요',to_timestamp('20/11/27 11:07:09.000000000','RR/MM/DD HH24:MI:SSXFF'),null);
Insert into BOOT.BOARD (BOARD_NUM,BOARD_WRITER,BOARD_SUBJECT,BOARD_CONTENT,BOARD_DATE,BOARD_FILE) values (48,'hello','좋은 날씨','오늘 날씨가 참 맑아요',to_timestamp('20/11/27 11:07:09.000000000','RR/MM/DD HH24:MI:SSXFF'),null);
Insert into BOOT.BOARD (BOARD_NUM,BOARD_WRITER,BOARD_SUBJECT,BOARD_CONTENT,BOARD_DATE,BOARD_FILE) values (49,'hello','좋은 날씨','오늘 날씨가 참 맑아요',to_timestamp('20/11/27 11:07:09.000000000','RR/MM/DD HH24:MI:SSXFF'),null);
Insert into BOOT.BOARD (BOARD_NUM,BOARD_WRITER,BOARD_SUBJECT,BOARD_CONTENT,BOARD_DATE,BOARD_FILE) values (52,'hello','주말입니다','좋은 주말보내세요~',to_timestamp('20/11/27 11:07:21.000000000','RR/MM/DD HH24:MI:SSXFF'),null);
Insert into BOOT.BOARD (BOARD_NUM,BOARD_WRITER,BOARD_SUBJECT,BOARD_CONTENT,BOARD_DATE,BOARD_FILE) values (53,'hello','주말입니다','좋은 주말보내세요~',to_timestamp('20/11/27 11:07:21.000000000','RR/MM/DD HH24:MI:SSXFF'),null);
Insert into BOOT.BOARD (BOARD_NUM,BOARD_WRITER,BOARD_SUBJECT,BOARD_CONTENT,BOARD_DATE,BOARD_FILE) values (54,'hello','주말입니다','좋은 주말보내세요~',to_timestamp('20/11/27 11:07:22.000000000','RR/MM/DD HH24:MI:SSXFF'),null);
Insert into BOOT.BOARD (BOARD_NUM,BOARD_WRITER,BOARD_SUBJECT,BOARD_CONTENT,BOARD_DATE,BOARD_FILE) values (55,'hello','주말입니다','좋은 주말보내세요~',to_timestamp('20/11/27 11:07:22.000000000','RR/MM/DD HH24:MI:SSXFF'),null);
Insert into BOOT.BOARD (BOARD_NUM,BOARD_WRITER,BOARD_SUBJECT,BOARD_CONTENT,BOARD_DATE,BOARD_FILE) values (56,'hello','주말입니다','좋은 주말보내세요~',to_timestamp('20/11/27 11:07:22.000000000','RR/MM/DD HH24:MI:SSXFF'),null);
Insert into BOOT.BOARD (BOARD_NUM,BOARD_WRITER,BOARD_SUBJECT,BOARD_CONTENT,BOARD_DATE,BOARD_FILE) values (57,'hello','주말입니다','좋은 주말보내세요~',to_timestamp('20/11/27 11:07:22.000000000','RR/MM/DD HH24:MI:SSXFF'),null);
Insert into BOOT.BOARD (BOARD_NUM,BOARD_WRITER,BOARD_SUBJECT,BOARD_CONTENT,BOARD_DATE,BOARD_FILE) values (61,'hello','주말입니다','좋은 주말보내세요~',to_timestamp('20/11/27 11:07:23.000000000','RR/MM/DD HH24:MI:SSXFF'),null);
Insert into BOOT.BOARD (BOARD_NUM,BOARD_WRITER,BOARD_SUBJECT,BOARD_CONTENT,BOARD_DATE,BOARD_FILE) values (62,'hello','주말입니다','좋은 주말보내세요~',to_timestamp('20/11/27 11:07:23.000000000','RR/MM/DD HH24:MI:SSXFF'),null);
Insert into BOOT.BOARD (BOARD_NUM,BOARD_WRITER,BOARD_SUBJECT,BOARD_CONTENT,BOARD_DATE,BOARD_FILE) values (63,'hello','주말입니다','좋은 주말보내세요~',to_timestamp('20/11/27 11:07:23.000000000','RR/MM/DD HH24:MI:SSXFF'),null);
Insert into BOOT.BOARD (BOARD_NUM,BOARD_WRITER,BOARD_SUBJECT,BOARD_CONTENT,BOARD_DATE,BOARD_FILE) values (64,'hello','주말입니다','좋은 주말보내세요~',to_timestamp('20/11/27 11:07:24.000000000','RR/MM/DD HH24:MI:SSXFF'),null);
Insert into BOOT.BOARD (BOARD_NUM,BOARD_WRITER,BOARD_SUBJECT,BOARD_CONTENT,BOARD_DATE,BOARD_FILE) values (65,'hello','주말입니다','좋은 주말보내세요~',to_timestamp('20/11/27 11:07:24.000000000','RR/MM/DD HH24:MI:SSXFF'),null);
Insert into BOOT.BOARD (BOARD_NUM,BOARD_WRITER,BOARD_SUBJECT,BOARD_CONTENT,BOARD_DATE,BOARD_FILE) values (66,'hello','주말입니다','좋은 주말보내세요~',to_timestamp('20/11/27 11:07:24.000000000','RR/MM/DD HH24:MI:SSXFF'),null);
Insert into BOOT.BOARD (BOARD_NUM,BOARD_WRITER,BOARD_SUBJECT,BOARD_CONTENT,BOARD_DATE,BOARD_FILE) values (67,'hello','주말입니다','좋은 주말보내세요~',to_timestamp('20/11/27 11:07:24.000000000','RR/MM/DD HH24:MI:SSXFF'),null);
Insert into BOOT.BOARD (BOARD_NUM,BOARD_WRITER,BOARD_SUBJECT,BOARD_CONTENT,BOARD_DATE,BOARD_FILE) values (68,'hello','게임하자','오늘은 무엇을 할까요~',to_timestamp('20/11/27 11:08:40.000000000','RR/MM/DD HH24:MI:SSXFF'),null);
Insert into BOOT.BOARD (BOARD_NUM,BOARD_WRITER,BOARD_SUBJECT,BOARD_CONTENT,BOARD_DATE,BOARD_FILE) values (71,'hello','게임하자','오늘은 무엇을 할까요~',to_timestamp('20/11/27 11:08:41.000000000','RR/MM/DD HH24:MI:SSXFF'),'16ITc0G.jpg');
Insert into BOOT.BOARD (BOARD_NUM,BOARD_WRITER,BOARD_SUBJECT,BOARD_CONTENT,BOARD_DATE,BOARD_FILE) values (72,'hello','수정한 게시글','알찬 주말일세ㅇㅋ',to_timestamp('20/11/27 11:08:42.000000000','RR/MM/DD HH24:MI:SSXFF'),'▶(주)두손소프트 구인접수카드.xls');
Insert into BOOT.BOARD (BOARD_NUM,BOARD_WRITER,BOARD_SUBJECT,BOARD_CONTENT,BOARD_DATE,BOARD_FILE) values (77,'hello','1','오늘은 무엇을 할까요~',to_timestamp('20/11/27 11:08:43.000000000','RR/MM/DD HH24:MI:SSXFF'),'dog bag.gif');
Insert into BOOT.BOARD (BOARD_NUM,BOARD_WRITER,BOARD_SUBJECT,BOARD_CONTENT,BOARD_DATE,BOARD_FILE) values (1,'hello','123','4123',to_timestamp('20/11/26 11:08:31.000000000','RR/MM/DD HH24:MI:SSXFF'),'ResumeMng.html');
Insert into BOOT.BOARD (BOARD_NUM,BOARD_WRITER,BOARD_SUBJECT,BOARD_CONTENT,BOARD_DATE,BOARD_FILE) values (2,'hello','123','4123',to_timestamp('20/11/26 11:08:45.000000000','RR/MM/DD HH24:MI:SSXFF'),'ResumeMng.html');
REM INSERTING into BOOT.BOARD_COMMENT
SET DEFINE OFF;
Insert into BOOT.BOARD_COMMENT (COMMENT_NUM,COMMENT_WRITER,COMMENT_CONTENT,COMMENT_DATE,BOARD_NUM,COMMENT_REF,COMMENT_LEVEL,COMMENT_LENGTH) values (41,'hello','게시글 잘 보았습니다~~',to_timestamp('20/11/29 21:17:31.000000000','RR/MM/DD HH24:MI:SSXFF'),77,41,0,0);
Insert into BOOT.BOARD_COMMENT (COMMENT_NUM,COMMENT_WRITER,COMMENT_CONTENT,COMMENT_DATE,BOARD_NUM,COMMENT_REF,COMMENT_LEVEL,COMMENT_LENGTH) values (42,'hello','내일은 평일이네요 ㅠㅠ',to_timestamp('20/11/29 21:17:38.000000000','RR/MM/DD HH24:MI:SSXFF'),77,38,1,1);
Insert into BOOT.BOARD_COMMENT (COMMENT_NUM,COMMENT_WRITER,COMMENT_CONTENT,COMMENT_DATE,BOARD_NUM,COMMENT_REF,COMMENT_LEVEL,COMMENT_LENGTH) values (38,'hello','오늘은 주말',to_timestamp('20/11/29 18:03:19.000000000','RR/MM/DD HH24:MI:SSXFF'),77,38,0,0);
Insert into BOOT.BOARD_COMMENT (COMMENT_NUM,COMMENT_WRITER,COMMENT_CONTENT,COMMENT_DATE,BOARD_NUM,COMMENT_REF,COMMENT_LEVEL,COMMENT_LENGTH) values (61,'hello','안냐세유ㅠㅠ',to_timestamp('20/11/30 16:30:28.000000000','RR/MM/DD HH24:MI:SSXFF'),77,38,2,2);
Insert into BOOT.BOARD_COMMENT (COMMENT_NUM,COMMENT_WRITER,COMMENT_CONTENT,COMMENT_DATE,BOARD_NUM,COMMENT_REF,COMMENT_LEVEL,COMMENT_LENGTH) values (62,'hello','쿠쿸',to_timestamp('20/11/30 16:30:36.000000000','RR/MM/DD HH24:MI:SSXFF'),77,41,1,1);
REM INSERTING into BOOT.MEMBER
SET DEFINE OFF;
Insert into BOOT.MEMBER (ID,PWD,ENABLED,AUTHORITY) values ('hello','$2a$10$f6fJ8r2Dy0nYJ2IVqq7/wOXoFim53NqY.xjpnEvmoIQmWFHgJSiQ.',1,'MEMBER');
Insert into BOOT.MEMBER (ID,PWD,ENABLED,AUTHORITY) values ('manager','$2a$10$uIhADV17eH17mpTE6aCyc.rjzuSfXzys1pT4T.5iwUedNqMz/VR/e',1,'ADMIN');
REM INSERTING into BOOT.START_TABLE
SET DEFINE OFF;
Insert into BOOT.START_TABLE (SUBJECT,POST) values ('hi','hello');
--------------------------------------------------------
--  Constraints for Table BOARD
--------------------------------------------------------

  ALTER TABLE "BOOT"."BOARD" ADD PRIMARY KEY ("BOARD_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BOARD_COMMENT
--------------------------------------------------------

  ALTER TABLE "BOOT"."BOARD_COMMENT" ADD PRIMARY KEY ("COMMENT_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table START_TABLE
--------------------------------------------------------

  ALTER TABLE "BOOT"."START_TABLE" ADD PRIMARY KEY ("SUBJECT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "BOOT"."MEMBER" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BOARD
--------------------------------------------------------

  ALTER TABLE "BOOT"."BOARD" ADD CONSTRAINT "CON_WRITER" FOREIGN KEY ("BOARD_WRITER")
	  REFERENCES "BOOT"."MEMBER" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BOARD_COMMENT
--------------------------------------------------------

  ALTER TABLE "BOOT"."BOARD_COMMENT" ADD CONSTRAINT "CON_BOARD" FOREIGN KEY ("BOARD_NUM")
	  REFERENCES "BOOT"."BOARD" ("BOARD_NUM") ON DELETE CASCADE ENABLE;
